sonata_admin:
    title: 'Sonata Admin'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]


#data_dog_audit:
#    audited_entities:
#        - AppBundle\Entity\Article
#    unaudited_entities:
#        - AppBundle\Entity\User
#        - ADW\UserBundle\Entity\AdminUser

sonata_doctrine_orm_admin:
    audit:
        force: false