version: '3.7'

services:
  app:
    image: php72
    build:
      context: .docker/php/
    working_dir: /var/www/
    depends_on:
      - database
    volumes:
      - ./:/var/www/:rw,cached
      - ./.docker/php/fpm/php.ini:/usr/local/etc/php/php.ini
      - ./.docker/php/fpm/php-fpm.conf:/usr/local/etc/php/7.2/fpm/php-fpm.conf
      - ./.docker/supervisor/php-fpm.conf:/etc/supervisor.d/php-fpm.ini

  app_cli:
    image: php72
    build:
      context: .docker/php/
    user: www-data
    working_dir: /var/www/
    depends_on:
      - database
    command: "/bin/bash -c 'while true; do sleep 30; done;'"
    volumes:
      - ./:/var/www/:rw,cached
      - ./.docker/php/fpm/php.ini:/usr/local/etc/php/php.ini
      - ./.docker/php/fpm/php-fpm.conf:/usr/local/etc/php/7.2/fpm/php-fpm.conf
      - ./.docker/supervisor/php-fpm.conf:/etc/supervisor.d/php-fpm.ini

  nginx:
    image: nginx:1.15
    depends_on:
      - app
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/:rw,cached
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./var/log/nginx/:/var/log/nginx:rw,delegated

  database:
    image: mysql:5.7
    command: --sql_mode=""
    volumes:
      - ./var/data/database:/var/lib/mysql:rw,delegated
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: study-project

networks:
  default:
    driver: bridge